[workspace]

members = [
  "./encode",
  "./buffer",
  "./xor",
  "./1-3-cipher",
  "./1-4-cipher",
  "./1-5-cipher",
  "./1-6-cipher",
  "./1-7-cipher",
  "./1-8-cipher",
  "./2-1-solution",
  "./2-2-solution",
]