[package]
name = "1-6-cipher"
version = "0.0.0"

[[bin]]
name = "1-6-cipher"
path = "./src/main.rs"

[dependencies]
xor = { path = "../xor" }
encode = { path = "../encode" }
buffer = { path = "../buffer" }
base64 = "0.11.0"