[package]
name = "xor"
version = "0.0.1"
authors = ["Allan Calix <contact@allancalix.com>"]

[dependencies]
"encode" = { "path" = "../encode" }
"buffer" = { "path" = "../buffer" }
openssl = { version = "0.10" }